### ISSUE TITLE
Update .prow.yaml with v0.3.2 changes across the repos

### ISSUE THREAD

**Issue by tumido** [operate-first/toolbox#18]
SSIA

- [x] operate-first/continuous-deployment#120
- [x] operate-first/support#105
- [x] operate-first/workshop-apps#26
- [x] operate-first/argocd-apps#89
- [x] operate-first/apps#303
- [x] operate-first/blueprint#47
- [x] operate-first/toolbox#21

**Comment by HumairAK** [comment]
Done -- thanks @tumido !
